[package]
name = "board-sabotter"
version = "0.1.0"
edition = "2021"

[dependencies] 
esp-idf-svc = {version = "0.51", features = ["experimental", "alloc"]}
log = "0.4"
embedded-hal = "1.0.0"
embedded-hal-bus = { version = "0.3.0", features = ["std"] }
vlx = { path = "../../devices/vlx" }
tca6408 = { path = "../../devices/tca6408" }
esp32_encoder = { path = "../../devices/esp32_encoder" }

[build-dependencies]
embuild = {version = "0.33.1", features = ["espidf"]}